[project]
name = "trampoline"
version = "0.1.0"
description = "A way to run .yay scripts!"
authors = [
    {name = "AlÃ­ Sinisterra",email = "haidarconh@gmail.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]


[tool.poetry]
package-mode = false
